name: Pingpong

on: 
  push: 
    branches: [dev]
  
  pull_request: 
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: crazy-max/setup-cmake@v1
      with:
        cmake-version: 3.21

    - name: Configure and build
      run: |
        cmake .
        make

